feature: Added requests and tests
vladsav33/java-shareit pull request #3
Opened 2023-06-17 17:08 UTC by vladsav33

2023-06-19 16:49 UTC, AnastasiyaFomkina requested changes

2023-06-19 16:49 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +/*    @ExceptionHandler(DuplicateEmail.class)
Нужно удалять код, а не комментировать его

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +@Data
Лучше не использовать `@Data`, так как она несет за собой много скрытых проблем. Вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
Нужно вынести в отдельный класс и сделать публичной константой

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                        .stream().map(itemMapper::toItemDto).collect(Collectors.toList())));
```suggestion
                        .stream()
                            .map(itemMapper::toItemDto)
                            .collect(Collectors.toList())));
```

Поправь стримы ниже

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .map(itemRequestMapper::toRequestDto).collect(Collectors.toList());
Лучше бить стрим по строкам, так его удобнее читать
```suggestion
                .map(itemRequestMapper::toRequestDto)
                .collect(Collectors.toList());
```

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +                        .header("X-Sharer-User-Id", userId)
[Замени](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html#replace_search_string_in_project) `"X-Sharer-User-Id"` на `HEADER` во всех тестах

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +    void testMapper() {
Больше похоже на тест ради теста,  нужно переименовать метод и добавить кейсы, где будет проверяться корректность маппинга из одной сущности в другую. Все настройки (получение маппера) нужно вынести в переменные класса или метод `@BeforeEach`

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    ItemRepository itemRepository;
Не хватает модификатора доступа

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    private Item item;
`item` и `owner` нужно убрать в метод `initTest`, так как больше нигде не используются

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    private UserDto owner;
`item` и `owner` нужно убрать в метод `initTest`, так как больше нигде не используются

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +        assertThat(ItemMapper.INSTANCE.toItemDto(bookingToCheck.getItem()), equalTo(booking.getItem()));
Проверки со строк 62-67 повторяются ниже, нужно вынести их в отдельный метод и переиспользовать, а не дублировать

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
>      private ItemDto itemDto;
`itemId`, `bookerDto` и `itemDto` нужно убрать в метод `initTest`, так как больше нигде не используются
поле `ownerDto` нужно удалить

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
>          when(itemService.isItemAvailable(any(Long.class))).thenReturn(true);
Повторяющиеся условия нужно выделить в отдельный метод и переиспользовать, а не дублировать

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +            List<BookingDto> bookingsToGet = bookingService.getBookingsByUser(bookerId, "UNKNOWN", page);
```suggestion
             bookingService.getBookingsByUser(bookerId, "UNKNOWN", page);
```
переменная не используется, соответсвенно создавать ее не нужно

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/component/ComponentTest.java
> +    private Item item;
Нужно убрать в метод `initTest` все лишние здесь переменные

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/component/ComponentTest.java
> +        List<Booking> bookings = bookingsCurrent.findBookings(booker.getId(), page).stream()
Стримы нужно побить по строкам для лучшей читаемости кода

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/component/ComponentTest.java
> +        assertEquals(bookingsCurrent.getState(), State.CURRENT);
Повторяющиеся проверки нужно вынести в отдельный метод.
В методы можно передавать параметры, поэтому 
`assertEquals(bookingsCurrent.getState(), State.CURRENT);` и  
`assertEquals(bookingsFuture.getState(), State.FUTURE); ` можно считать одинаковыми проверками

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/CommentMapperTest.java
> +    void testMapper() {
Нужно разбить большой тест на логические составляющие. Сложно поддерживать тест, в котором проверяется все в одной куче

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemMapperTest.java
> +    void testMapper() {
Нужно доработать тест

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    private UserDto user;
Нужно убрать в initTest

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    private long userId;
Нужно удалить

2023-06-19 16:49 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +        assertThat(itemToCheck.getId(), notNullValue());
Нужно избавиться от дублирующих проверок

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    UserServiceImpl userService;
Не хватает модификатора доступа

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +            ItemDto itemToCreate = itemService.createItem(userId, itemDto);
Нужно удалить неиспользуемые переменные здесь и ниже

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +        ItemDto itemToCreate = ItemDto.builder().id(itemId).name("Дрель аккумуляторная").description("description")
Нужно вынести повторяющиеся объекты в `BeforeEach`

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/RequestMapperTest.java
> +    void testMapper() {
Нужно доработать тест

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/RequestServiceIntegrationTest.java
> +    private long userId;
Не используется

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/RequestServiceIntegrationTest.java
> +    private ItemRequestDto request;
30 и 31 в initTest

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/RequestServiceIntegrationTest.java
> +public class RequestServiceIntegrationTest {
Нужно добавить тесты на все методы сервиса `ItemRequestService`

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/user/UserMapperTest.java
> +    void testMapper() {
Нужно доработать

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +    void testCreateUserNonUniqueEmail() {
Код нужно удалять

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +            User userToCheck = query.setParameter("email", userToCreate.getEmail()).getSingleResult();
Лишняя переменная

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +        TypedQuery<User> query = em.createQuery("Select u from User u where u.email = :email", User.class);
Во всех тестах нужно проверять уже существующую логику,  `entity manager` и запросы к базе в тестах нужно удалить из всех тестов

2023-06-19 16:49 UTC, AnastasiyaFomkina commented on pom.xml
> +			<artifactId>hibernate-entitymanager</artifactId>
Не должен использоваться в тестах, нужно удалить и переписать тесты, в которых сейчас вручную прописываются запросы к базе.
Такие тесты не проверяют функционал приложения, а только запросы, которые написаны в самих тестах

2023-06-20 07:52 UTC, vladsav33 commented on src/test/java/ru/practicum/shareit/request/RequestServiceIntegrationTest.java
> +public class RequestServiceIntegrationTest {
Тесты на все методы сервиса ItemRequestService находятся в ItemRequestServiceTest. В данном тесте проверяется только сохранение в БД.

2023-06-20 07:55 UTC, vladsav33 commented on pom.xml
> +			<artifactId>hibernate-entitymanager</artifactId>
Запросы к БД сделаны в соответствии с материалом и примером, приведенным в теоретическом материале.

2023-06-20 18:01 UTC, AnastasiyaFomkina requested changes

2023-06-20 18:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/controllers/ItemRequestController.java
> +    public final ItemRequestService itemRequestService;
```suggestion
    private final ItemRequestService itemRequestService;
```

2023-06-20 18:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public final ItemMapper itemMapper;
Лучше максимально скрывать все поля класса, чтобы сделать программу безопасной и избежать множественных багов. 

В редких случаях поля класса могут иметь модификатор доступа 
* `protected` - если данные поля будут как-либо переопределяться наследниками
* `public`- если поле считается константой и используется по всему проекту

Поправь, пожалуйста, модификаторы переменных класса на `private`

2023-06-20 18:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/request/RequestMapperTest.java
> +    ItemRequest request;
Не хватает модификаторов доступа у полей класса

2023-06-20 18:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/CommentMapperTest.java
> +    CommentMapper mapper;
Не хватает модификатора доступа

2023-06-20 21:03 UTC, AnastasiyaFomkina approved these changes

2023-06-21 08:59 UTC, merged